# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2023-11-23 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rango', '0006_auto_20231123_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user_likes',
            field=models.ManyToManyField(related_name='category_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='category',
            name='likes',
        ),
        migrations.AddField(
            model_name='category',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
